apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sentinel-iot.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sentinel-iot.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.pdb.backend.minAvailable }}
  selector:
    matchLabels:
      {{- include "sentinel-iot.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sentinel-iot.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sentinel-iot.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: {{ .Values.pdb.frontend.minAvailable }}
  selector:
    matchLabels:
      {{- include "sentinel-iot.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
