#!/bin/sh
# Runs inside the eclipse-mosquitto container before the broker starts.
#
# Responsibilities:
#   1. Provision the password file from environment variables.
#   2. Provision per-device MQTT accounts from MQTT_DEVICE_CREDENTIALS.
#   3. Generate a runtime ACL that includes per-device topic rules.
#   4. Build a runtime broker config — enforces TLS when MQTT_TLS_REQUIRED=true,
#      enables mTLS (client certificate verification) when MQTT_MTLS_ENABLED=true,
#      and removes the plaintext listener when TLS-only mode is active.
#
# Environment variables:
#   MQTT_USER              Backend service account username (default: sentinel-backend)
#   MQTT_PASS              Backend service account password (default: changeme)
#   MQTT_DEVICE_USER       Shared device fallback username   (default: sentinel-device)
#   MQTT_DEVICE_PASS       Shared device fallback password   (default: changeme)
#   MQTT_DEVICE_CREDENTIALS  Per-device credentials: "sensor-1:pass1,sensor-2:pass2"
#                            Each device gets its own account and ACL entry.
#   MQTT_TLS_REQUIRED      "true" → broker refuses to start without certs (default: false)
#   MQTT_MTLS_ENABLED      "true" → clients must present a valid certificate (default: false)
#                            Requires running gen-mqtt-certs.sh --with-client-certs first.
#
# TLS setup:
#   Run:  bash scripts/gen-mqtt-certs.sh
#   Then: MQTT_TLS_REQUIRED=true docker compose up mosquitto
set -eu

PASSWD_FILE="/mosquitto/data/passwd"
CERTS_DIR="/mosquitto/certs"
RUNTIME_CONFIG="/mosquitto/data/runtime.conf"
RUNTIME_ACL="/mosquitto/data/runtime.acl"

# ── 1. Provision backend service account ────────────────────────────────────
echo "[entrypoint] Provisioning MQTT password file..."
rm -f "$PASSWD_FILE"
mosquitto_passwd -b -c "$PASSWD_FILE" \
  "${MQTT_USER:-sentinel-backend}" "${MQTT_PASS:-changeme}"

# ── 2. Provision shared device fallback account ──────────────────────────────
mosquitto_passwd -b "$PASSWD_FILE" \
  "${MQTT_DEVICE_USER:-sentinel-device}" "${MQTT_DEVICE_PASS:-changeme}"

# ── 3. Provision per-device accounts ────────────────────────────────────────
# Format: "sensor-1:pass1,sensor-2:pass2,sensor-3:pass3"
# Each device gets its own Mosquitto account — no shared credentials.
if [ -n "${MQTT_DEVICE_CREDENTIALS:-}" ]; then
  echo "[entrypoint] Provisioning per-device accounts..."
  printf '%s' "$MQTT_DEVICE_CREDENTIALS" | tr ',' '\n' > /tmp/_dev_creds
  while IFS= read -r entry; do
    dev_id="${entry%%:*}"
    dev_pass="${entry#*:}"
    # Guard: skip empty entries or malformed lines (no colon separator)
    if [ -z "$dev_id" ] || [ -z "$dev_pass" ] || [ "$dev_id" = "$dev_pass" ]; then
      continue
    fi
    mosquitto_passwd -b "$PASSWD_FILE" "$dev_id" "$dev_pass"
    echo "[entrypoint] Provisioned device account: $dev_id"
  done < /tmp/_dev_creds
  rm -f /tmp/_dev_creds
fi

chown mosquitto:mosquitto "$PASSWD_FILE"
chmod 600 "$PASSWD_FILE"
echo "[entrypoint] Password file written."

# ── 4. Build runtime ACL (base rules + per-device entries) ──────────────────
cp /mosquitto/config/acl "$RUNTIME_ACL"

if [ -n "${MQTT_DEVICE_CREDENTIALS:-}" ]; then
  printf '\n# Per-device ACL entries (auto-generated by docker-entrypoint.sh)\n' >> "$RUNTIME_ACL"
  printf '%s' "$MQTT_DEVICE_CREDENTIALS" | tr ',' '\n' > /tmp/_dev_creds
  while IFS= read -r entry; do
    dev_id="${entry%%:*}"
    dev_pass="${entry#*:}"
    if [ -z "$dev_id" ] || [ -z "$dev_pass" ] || [ "$dev_id" = "$dev_pass" ]; then
      continue
    fi
    printf '\nuser %s\ntopic write factory/telemetry\n' "$dev_id" >> "$RUNTIME_ACL"
  done < /tmp/_dev_creds
  rm -f /tmp/_dev_creds
fi

# ── 5. Build runtime broker config ──────────────────────────────────────────
TLS_REQUIRED="${MQTT_TLS_REQUIRED:-false}"
MTLS_ENABLED="${MQTT_MTLS_ENABLED:-false}"

# Determine if TLS certs are available
HAS_CERTS="false"
if [ -f "$CERTS_DIR/ca.crt" ] && [ -f "$CERTS_DIR/server.crt" ] && [ -f "$CERTS_DIR/server.key" ]; then
  HAS_CERTS="true"
fi

# Fail fast if TLS is required but certs are missing
if [ "$TLS_REQUIRED" = "true" ] && [ "$HAS_CERTS" = "false" ]; then
  echo "[entrypoint] ERROR: MQTT_TLS_REQUIRED=true but no certificates found in $CERTS_DIR"
  echo "[entrypoint] Generate certs first:  bash scripts/gen-mqtt-certs.sh"
  echo "[entrypoint] For mTLS client certs: bash scripts/gen-mqtt-certs.sh --with-client-certs"
  exit 1
fi

cat > "$RUNTIME_CONFIG" <<EOF
# Runtime config generated by docker-entrypoint.sh — do not edit manually.
allow_anonymous false
password_file $PASSWD_FILE
acl_file $RUNTIME_ACL

persistence true
persistence_location /mosquitto/data/

log_type error
log_type warning
log_type notice
log_type information
EOF

# Add plaintext listener only when NOT in TLS-required mode
if [ "$TLS_REQUIRED" != "true" ]; then
  cat >> "$RUNTIME_CONFIG" <<EOF

# Plaintext listeners (dev/local only — disable in production with MQTT_TLS_REQUIRED=true)
listener 1883
listener 9001
protocol websockets
EOF
fi

# Add TLS listener if certs are present
if [ "$HAS_CERTS" = "true" ]; then
  if [ "$MTLS_ENABLED" = "true" ]; then
    REQUIRE_CERT="true"
    echo "[entrypoint] mTLS enabled (MQTT_MTLS_ENABLED=true) — clients must present a valid certificate"
  else
    REQUIRE_CERT="false"
  fi

  cat >> "$RUNTIME_CONFIG" <<EOF

# TLS listener — activated because certs exist in $CERTS_DIR
listener 8883
protocol mqtt
cafile $CERTS_DIR/ca.crt
certfile $CERTS_DIR/server.crt
keyfile $CERTS_DIR/server.key
require_certificate $REQUIRE_CERT
tls_version tlsv1.3
EOF
  echo "[entrypoint] TLS listener enabled on :8883 (require_certificate=$REQUIRE_CERT)"
else
  echo "[entrypoint] No certs in $CERTS_DIR — TLS listener skipped (plaintext only)"
  echo "[entrypoint] To enable TLS: bash scripts/gen-mqtt-certs.sh && docker compose restart mosquitto"
fi

chown mosquitto:mosquitto "$RUNTIME_ACL" "$RUNTIME_CONFIG"
chmod 600 "$RUNTIME_ACL" "$RUNTIME_CONFIG"
exec mosquitto -c "$RUNTIME_CONFIG"
